spring.application.name=inscripciones
server.port=8080

# Configuracion de RabbitMQ
spring.rabbitmq.host=172.17.0.1
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

# Configuracion base de datos
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.OracleDialect

# Configuraciones JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Configuraciones HikariCP
spring.datasource.hikari.connection-test-query=SELECT 1 FROM DUAL
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.connection-timeout=20000
spring.datasource.hikari.max-lifetime=1800000
spring.datasource.hikari.pool-name=HikariPool

# Session config
spring.session.jdbc.initialize-schema=always
spring.sql.init.mode=always
spring.sql.init.platform=oracle

# Issuer de JWT
spring.security.oauth2.resourceserver.jwt.issuer-uri=${ISSUER}
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=${JWKS_URI}

# Importar variables de entorno desde archivo .env para despliegue local
spring.config.import=optional:file:.env[.properties]